introduce debouncing (300ms) for currency input
tempus-finance/tempus-app pull request #1254
Opened 2022-03-24 22:00 UTC by ShawTim

2022-03-24 22:07 UTC, lazarmitic requested changes

2022-03-24 22:07 UTC, lazarmitic commented on packages/tempus-client_v2/src/components/currencyInput/currencyInput.tsx
> +  const [time, setTime] = useState<NodeJS.Timeout>();
Variable `time` is not affecting component render output, so instead of using state to store it, you should use ref.

By using ref we are going to avoid unnecessary re-render every time `time` variable is changed.

2022-03-24 22:15 UTC, ShawTim commented on packages/tempus-client_v2/src/components/currencyInput/currencyInput.tsx
> +  const [time, setTime] = useState<NodeJS.Timeout>();
good catch ser! `useState` trigger rerender which is not required here.

2022-03-24 22:25 UTC, ShawTim commented on packages/tempus-client_v2/src/components/currencyInput/currencyInput.tsx
> +  const [time, setTime] = useState<NodeJS.Timeout>();
fixed

2022-03-25 09:34 UTC, danieledamiani approved these changes

2022-03-25 11:04 UTC, lazarmitic approved these changes

2022-03-25 11:05 UTC, merged