Add toggle switch component
tempus-finance/tempus-app pull request #1325
Opened 2022-03-29 14:34 UTC by iamvukasin

2022-03-29 15:14 UTC, danieledamiani commented on packages/tempus-client_v3/src/components/ToggleSwitch/index.ts
> +import ToggleSwitch from './ToggleSwitch';
is the `ToggleSwitch` going to be "shared"?

2022-03-29 15:20 UTC, danieledamiani commented on packages/tempus-client_v3/src/components/shared/Shadow/index.ts
> +if (root) {
this function looks pretty similar to the other we use to load up the colours...

2022-03-29 15:21 UTC, danieledamiani reviewed
a few comments, in general lgtm

2022-03-30 08:31 UTC, lazarmitic requested changes

2022-03-30 08:31 UTC, lazarmitic commented on packages/tempus-client_v3/src/components/ToggleSwitch/ToggleSwitch.tsx
> +const ToggleSwitch = (props: ToggleSwitchProps & React.HTMLProps<HTMLInputElement>) => {
Use FC to define props for a functional component - this way you are overriding children and some other built in props.

Let's not use ...checkBox props - define manually only what you need instead of importing all checkbox props into a component.

2022-03-30 08:31 UTC, lazarmitic commented on packages/tempus-client_v3/src/components/shared/Color/colors.json
> +  "greyLight": "#BFC0C0"
Let's avoid using colors that have actual color value in their name - in this case 'gray' - name this color based on usage - later on when we add dark theme, we only need to update color values and names can stay the same.

2022-03-30 08:31 UTC, lazarmitic commented on packages/tempus-client_v3/src/components/ToggleSwitch/ToggleSwitch.tsx
> +          <Typography
Use weight property to make text bold `weight: {checked ? 'bold' : 'regular'}`, this will also help you with getting rid of !important flag in CSS.

2022-03-30 08:31 UTC, lazarmitic commented on packages/tempus-client_v3/src/components/ToggleSwitch/ToggleSwitch.tsx
> +            className={`tc__toggle-switch__label ${checked ? 'tc__toggle-switch__label-selected' : ''}`}
Instead of modifying typography with left margin - set padding on parent component. (Or use Spacer component to add space between elements inside flexbox).

2022-03-30 09:40 UTC, lazarmitic approved these changes

2022-03-30 09:57 UTC, merged