Website 2.1.1
tempus-finance/tempus-app pull request #2299
Opened 2022-09-09 08:39 UTC by danieledamiani

2022-09-09 09:48 UTC, irinelT requested changes

2022-09-09 09:48 UTC, irinelT commented on .circleci/config.yml
> -
The latest `./circle/config.yml` is very important. Please use the latest one and change only what is necessary.

2022-09-12 09:15 UTC, danieledamiani commented on .circleci/config.yml
> -
restored

2022-09-14 13:29 UTC, irinelT approved these changes

2022-09-14 14:03 UTC, merged