Add profit/loss graph
tempus-finance/tempus-app pull request #469
Opened 2021-11-05 06:43 UTC by lazarmitic

2021-11-05 07:45 UTC, danieledamiani commented on packages/tempus-client_v2/src/utils/getPastDaysNumber.ts
> +  for (let i = 0; i < lastDaysCount; i += every) {
`for (let i = lastDaysCount - 1; i > 0; i -= every) {` and no need to do `.reverse();`

2021-11-05 07:54 UTC, danieledamiani commented on packages/tempus-client_v2/src/adapters/ProfitLossGraphDataAdapter.ts
> +      for (let i = 29; i > 0; i -= 2) {
`i` starts from `29` and decrements by `2` so this cycle will run 14 times, is this expected?

2021-11-05 07:56 UTC, lazarmitic commented on packages/tempus-client_v2/src/adapters/ProfitLossGraphDataAdapter.ts
> +      for (let i = 29; i > 0; i -= 2) {
Yes, I need to update the comment here.

2021-11-05 07:57 UTC, danieledamiani commented on packages/tempus-client_v2/src/components/profitLoss/ProfitLoss.tsx
> +        .subscribe(estimate => {
need to `unsubscribe` somewhere, maybe after line 39

2021-11-05 07:58 UTC, danieledamiani commented on packages/tempus-client_v2/src/components/profitLoss/ProfitLoss.tsx
> +        .subscribe(estimate => {
`const stream$ = poolDataAdapter
        .getEstimatedWithdrawAmoun ....`
`stream$.unsubscribe()`

2021-11-05 08:00 UTC, danieledamiani requested changes
a few comments

2021-11-08 10:58 UTC, lazarmitic commented on packages/tempus-client_v2/src/components/profitLoss/ProfitLoss.tsx
> +        .subscribe(estimate => {
fixed

2021-11-08 10:59 UTC, lazarmitic commented on packages/tempus-client_v2/src/utils/getPastDaysNumber.ts
> +  for (let i = 0; i < lastDaysCount; i += every) {
If want to have last 5 days and every 3 days and current date is 10th, result should be
`10 7`

With this change it will be `5 8`.

I should always have current day included, but if I start from the past there is a chance it will not be included if `every` is not set to `1`.

2021-11-08 11:01 UTC, lazarmitic commented on packages/tempus-client_v2/src/adapters/ProfitLossGraphDataAdapter.ts
> +      for (let i = 29; i > 0; i -= 2) {
fixed

2021-11-08 11:02 UTC, danieledamiani approved these changes

2021-11-08 11:03 UTC, merged