Move poolDataContext to Hookstate State
tempus-finance/tempus-app pull request #530
Opened 2021-11-23 08:50 UTC by lazarmitic

2021-11-23 10:14 UTC, danieledamiani commented on packages/tempus-client_v2/src/state/PoolDataState.ts
> +export interface StaticPoolStateData {
a more meaningful name would be `StaticPoolDataMap` or something similar

2021-11-23 10:15 UTC, danieledamiani commented on packages/tempus-client_v2/src/state/PoolDataState.ts
> +  precision: {
should this property be called `tokenPrecision` to be consistent?

2021-11-23 10:22 UTC, danieledamiani commented on packages/tempus-client_v2/src/state/PoolDataState.ts
> +export interface StaticPoolData {
actually `StaticPoolData` interface is the exact same as `TempusPool` type, so maybe no need to have both?

2021-11-23 10:23 UTC, danieledamiani commented on packages/tempus-client_v2/src/state/PoolDataState.ts
>    staticPoolDataStateInitialValue[tempusPoolConfig.address] = {
this can be simplified as:
```
staticPoolDataStateInitialValue[tempusPoolConfig.address] = { ...tempusPoolConfig };

2021-11-23 11:02 UTC, danieledamiani commented on packages/tempus-client_v2/src/components/buttons/Approve.tsx
> +  const backingToken = staticPoolData[selectedPool.get()].backingToken.attach(Downgraded).get();
what is the rationale behind this? I think `staticPoolData` is not going to change (hence is 'static')

2021-11-23 11:09 UTC, lazarmitic commented on packages/tempus-client_v2/src/components/buttons/Approve.tsx
> +  const backingToken = staticPoolData[selectedPool.get()].backingToken.attach(Downgraded).get();
Yes, we can omit whole staticState stuff and just use it directly from config. I realized this along the way, but it's going to take some time to change, so I just kept it. We can remove it down the line.

2021-11-23 12:34 UTC, danieledamiani commented on packages/tempus-client_v2/src/components/dashboard/dashboard.tsx
> +  const onApplyFilter = (filterData: FilterData | null) => {
why did you remove `useCallback`?

2021-11-23 12:41 UTC, danieledamiani commented on packages/tempus-client_v2/src/components/dashboard/providers/availableToDepositFormatter.tsx
> +  const getChildAvailableToDeposit = () => {
why remove `useMemo`? Every time we run line `82` we rerun this function

2021-11-23 12:45 UTC, danieledamiani requested changes
In general looks good but there are a few questions I'd like to be answered

2021-11-23 12:49 UTC, lazarmitic commented on packages/tempus-client_v2/src/components/dashboard/dashboard.tsx
> +  const onApplyFilter = (filterData: FilterData | null) => {
`negativeYieldPoolData` and `dynamicPoolData` reference never changes (state is created only once) and callback is not being updated properly, couple of solutions for this:

1. When setting state use spread operator to update whole state object every time - not good for performance.
2. Remove callback hook. - this component is no re-rendered a lot so even without useCallback performance is not affected a lot.
3. Use library that allows us to specify custom compare function for useCallback - this is best solution I think.

2021-11-23 12:51 UTC, lazarmitic commented on packages/tempus-client_v2/src/components/dashboard/providers/availableToDepositFormatter.tsx
> +  const getChildAvailableToDeposit = () => {
See response on above comment.

2021-11-23 12:51 UTC, lazarmitic commented
Added response to all comments.

2021-11-23 18:40 UTC, lazarmitic commented on packages/tempus-client_v2/src/state/PoolDataState.ts
> +export interface StaticPoolStateData {
fixed

2021-11-23 18:40 UTC, lazarmitic commented on packages/tempus-client_v2/src/state/PoolDataState.ts
> +  precision: {
fixed

2021-11-23 18:40 UTC, lazarmitic commented on packages/tempus-client_v2/src/state/PoolDataState.ts
> +export interface StaticPoolData {
fixed

2021-11-23 18:40 UTC, lazarmitic commented on packages/tempus-client_v2/src/state/PoolDataState.ts
>    staticPoolDataStateInitialValue[tempusPoolConfig.address] = {
fixed

2021-11-24 10:41 UTC, danieledamiani approved these changes

2021-11-24 12:17 UTC, merged