Add slippage option
tempus-finance/tempus-app pull request #545
Opened 2021-11-29 12:29 UTC by lazarmitic

2021-11-29 15:25 UTC, danieledamiani commented on packages/tempus-client_v2/src/components/percentageInput/percentageParser.ts
> +export const checkIfNumberRegExp = /\d/;
would be nice to have some unit tests for these functions

2021-11-29 15:26 UTC, danieledamiani commented on packages/tempus-client_v2/src/components/percentageInput/percentageParser.ts
> +      return value.toString();
if value is negative?

2021-11-29 15:33 UTC, danieledamiani commented on packages/tempus-client_v2/src/components/percentageInput/percentageInput.tsx
> +      const parsedPercentage = formatValueToPercentage(currentValue);
I think would be better to have `formatValueToPercentage` returning an object like `{ parsedValue: 1.23, parsedValueToPercentage: '123%' }` and then use these values in `setValue` and `onChange`. Doing math operation in a component should be avoided

2021-11-29 15:34 UTC, danieledamiani requested changes
a few questions and observations

2021-11-29 17:43 UTC, lazarmitic commented on packages/tempus-client_v2/src/adapters/UserBalanceDataAdapter.ts
> +          if (this.statisticsService && backingTokenRate && exitEstimate.tokenAmount) {
Yes, if call to fetch `exitEstimate` fails, `throwError()` would be called and execution will be stopped.

2021-11-29 17:46 UTC, lazarmitic commented on packages/tempus-client_v2/src/components/navbar/Settings.tsx
> +          slippage: Number(value),
Percentage input already handles value range (0-100), I will add additional check for negative values in PercentageInput parser.

2021-11-29 18:04 UTC, lazarmitic commented on packages/tempus-client_v2/src/components/percentageInput/percentageParser.ts
> +export const checkIfNumberRegExp = /\d/;
Unit tests added.

2021-11-29 18:05 UTC, lazarmitic commented on packages/tempus-client_v2/src/components/percentageInput/percentageParser.ts
> +      return value.toString();
Added check for negative values.

2021-11-29 18:16 UTC, lazarmitic commented on packages/tempus-client_v2/src/components/percentageInput/percentageInput.tsx
> +      const parsedPercentage = formatValueToPercentage(currentValue);
Fixed

2021-11-29 19:20 UTC, danieledamiani commented on packages/tempus-client_v2/src/components/percentageInput/percentageParser.test.ts
> +    { value: '', expected: { parsedValue: '', percentageValue: '' } },
is there a case when `parsedValue` is different from `percentageValue`?

2021-11-29 19:23 UTC, danieledamiani requested changes
one more question

2021-11-30 06:29 UTC, lazarmitic commented on packages/tempus-client_v2/src/components/percentageInput/percentageParser.test.ts
> +    { value: '', expected: { parsedValue: '', percentageValue: '' } },
oh yeah, I guess you are right, we don't have large numbers in PercentageParser like `100,100.20` (in this case `parsedValue = 100,100.20` and `percentageValue = 100100.20`). I will remove this code and remove regex from `onChange()` callback.

2021-11-30 06:38 UTC, lazarmitic commented on packages/tempus-client_v2/src/components/percentageInput/percentageParser.test.ts
> +    { value: '', expected: { parsedValue: '', percentageValue: '' } },
Fixed.

2021-11-30 08:19 UTC, danieledamiani commented on packages/tempus-client_v2/src/components/percentageInput/percentageInput.tsx
> +      onChange && onChange(parsedPercentage);
if `parsedPercentage` is falsy, is it ok to pass it to `onChange`? Otherwise we could move line 51 just below line 49

2021-11-30 08:20 UTC, danieledamiani requested changes
One more!

2021-11-30 08:22 UTC, lazarmitic commented
Fixed :D

2021-11-30 08:24 UTC, danieledamiani approved these changes

2021-11-30 08:27 UTC, merged