Withdraw function interface change
tempus-finance/tempus-app pull request #603
Opened 2021-12-10 14:37 UTC by lazarmitic

2021-12-10 14:43 UTC, danieledamiani commented on packages/tempus-client_v2/src/components/withdraw/Withdraw.tsx
> +        ethers.utils.parseEther(actualSlippage),
please use `parseUnit`

2021-12-10 14:43 UTC, danieledamiani requested changes
a comment

2021-12-10 14:44 UTC, lazarmitic commented on packages/tempus-client_v2/src/components/withdraw/Withdraw.tsx
> +        ethers.utils.parseEther(actualSlippage),
It's hardcoded on contract side to use 18 decimals for slippage, slippage is not a token, so no need to use token precision here.

2021-12-10 14:50 UTC, danieledamiani commented on packages/tempus-client_v2/src/components/withdraw/Withdraw.tsx
> +        ethers.utils.parseEther(actualSlippage),
then for consistency let's do `parseUnit(actualSlippage, 18)`

2021-12-13 09:19 UTC, lazarmitic commented on packages/tempus-client_v2/src/components/withdraw/Withdraw.tsx
> +        ethers.utils.parseEther(actualSlippage),
fixed

2021-12-13 09:33 UTC, danieledamiani approved these changes

2021-12-13 09:46 UTC, merged