Add sidebar tooltips
tempus-finance/tempus-app pull request #657
Opened 2021-12-23 15:29 UTC by danieledamiani

2021-12-24 10:56 UTC, lazarmitic requested changes

2021-12-24 10:56 UTC, lazarmitic commented on packages/tempus-client_v2/src/adapters/SidebarDataAdapter.ts
> +  getWithdrawDisabledReason(poolAddress: string): Words | null {
Same as deposit.

2021-12-24 10:56 UTC, lazarmitic commented on packages/tempus-client_v2/src/adapters/SidebarDataAdapter.ts
> +    const userLPTokenBalance = dynamicPoolDataState[poolAddress].userLPTokenBalance.get();
LP Tokens balance should not affect swap availability. You should only check if user has principals or yields balance available.

2021-12-24 10:56 UTC, lazarmitic commented on packages/tempus-client_v2/src/adapters/SidebarDataAdapter.ts
> +      return 'swapDisabledNoDeposit';
We should probably change this to `swapDisabledNoShares` or something similar.

2021-12-24 10:56 UTC, lazarmitic commented on packages/tempus-client_v2/src/adapters/SidebarDataAdapter.ts
> +  getSwapDisabledReason(poolAddress: string): Words | null {
Swap should be disabled if pool does not have any liquidity as well.

2021-12-24 10:56 UTC, lazarmitic commented on packages/tempus-client_v2/src/adapters/SidebarDataAdapter.ts
> +    if (
LP Tokens should not affect Provide Liquidity. We only need to check if principals or yields are available in user wallet.

2021-12-24 10:56 UTC, lazarmitic commented on packages/tempus-client_v2/src/components/sidebar/Sidebar.tsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
Since there is no dependency array, this useEffect will run on every re-render. In this case I don't think we need comment that disables ESLint.

2021-12-24 11:19 UTC, danieledamiani commented on packages/tempus-client_v2/src/adapters/SidebarDataAdapter.ts
> +  getDepositDisabledReason(poolAddress: string): Words | null {
fixed

2021-12-24 11:19 UTC, danieledamiani commented on packages/tempus-client_v2/src/adapters/SidebarDataAdapter.ts
> +  getWithdrawDisabledReason(poolAddress: string): Words | null {
fixed

2021-12-24 11:19 UTC, danieledamiani commented on packages/tempus-client_v2/src/adapters/SidebarDataAdapter.ts
> +    const userLPTokenBalance = dynamicPoolDataState[poolAddress].userLPTokenBalance.get();
fixed

2021-12-24 11:20 UTC, danieledamiani commented on packages/tempus-client_v2/src/adapters/SidebarDataAdapter.ts
> +      return 'swapDisabledNoDeposit';
fixed

2021-12-24 11:21 UTC, danieledamiani commented on packages/tempus-client_v2/src/adapters/SidebarDataAdapter.ts
> +  getSwapDisabledReason(poolAddress: string): Words | null {
we don't have a copy for that, will ask it

2021-12-24 11:23 UTC, danieledamiani commented on packages/tempus-client_v2/src/adapters/SidebarDataAdapter.ts
> +    if (
fixed

2021-12-24 11:29 UTC, lazarmitic commented on packages/tempus-client_v2/src/adapters/SidebarDataAdapter.ts
> +  getDepositDisabledReason(poolAddress: string): Words | null {
Yes

2022-01-04 14:02 UTC, danieledamiani commented on packages/tempus-client_v2/src/adapters/SidebarDataAdapter.ts
> +  getDepositDisabledReason(poolAddress: string): Words | null {
fixed

2022-01-04 14:03 UTC, danieledamiani commented on packages/tempus-client_v2/src/adapters/SidebarDataAdapter.ts
> +  getWithdrawDisabledReason(poolAddress: string): Words | null {
fixed

2022-01-04 14:05 UTC, danieledamiani commented on packages/tempus-client_v2/src/adapters/SidebarDataAdapter.ts
> +  getSwapDisabledReason(poolAddress: string): Words | null {
fixed

2022-01-04 14:06 UTC, danieledamiani commented on packages/tempus-client_v2/src/components/sidebar/Sidebar.tsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
it's to avoid typescript warnings

2022-01-10 09:52 UTC, lazarmitic approved these changes

2022-01-11 16:39 UTC, merged