feat: add ens name and avatar support
tempus-finance/tempus-app pull request #661
Opened 2021-12-30 12:45 UTC by bigint

![image](https://user-images.githubusercontent.com/69431456/147753112-88a23af5-c104-4df8-a5a4-0fdc9c9badbb.png)

2021-12-30 12:46 UTC, bigint commented
/cc @lazarmitic

2021-12-30 13:10 UTC, danieledamiani commented on packages/tempus-client_v2/src/components/wallet/Wallet.tsx
> +import Davatar from '@davatar/react';
please move the import above line 7

2021-12-30 13:11 UTC, danieledamiani commented on packages/tempus-client_v2/src/components/wallet/Wallet.tsx
> +import useENS from '../../utils/useENS';
please move this import above line 19

2021-12-30 13:13 UTC, danieledamiani commented on packages/tempus-client_v2/src/utils/useENS.ts
> +        const provider = new ethers.providers.JsonRpcProvider(NETWORK_URLS[1]);
this will work on mainnet only then?

2021-12-30 13:15 UTC, danieledamiani requested changes
a couple of comments and a question

2021-12-30 13:20 UTC, bigint commented on packages/tempus-client_v2/src/utils/useENS.ts
> +        const provider = new ethers.providers.JsonRpcProvider(NETWORK_URLS[1]);
They have support on rinkeby but that is vulnerable to use in prod!

All other major sites fetch it from mainnet rather than user-preferred network

2021-12-30 13:21 UTC, bigint commented
Thanks @danieledamiani addressed the comments 🙏🏻

2022-01-12 05:09 UTC, bigint commented
@danieledamiani any updates?

2022-01-15 14:53 UTC, bigint commented
@danieledamiani FYI I removed new dependency and built it from scratch 🤗

2022-01-17 18:51 UTC, ShawTim approved these changes
the dependency is removed, should be safe.

2022-01-17 19:35 UTC, lazarmitic approved these changes

2022-01-17 20:06 UTC, danieledamiani approved these changes
please don't merge it yet, will go in the next release

2022-01-19 09:11 UTC, merged