Update profit loss chart when user balance for pool changes
tempus-finance/tempus-app pull request #665
Opened 2022-01-01 09:19 UTC by lazarmitic

2022-01-03 10:50 UTC, danieledamiani commented on packages/tempus-client_v2/src/components/profitLoss/profitLossChart/ProfitLossChart.tsx
> +    if (!lastChartEntry) {
this value can be `undefined` only if `currentChartData.length === 0` but this is always false as you're checking this condition at line `51`. Is there a case where the last value of `chartData` returns a `null` value?

2022-01-03 10:51 UTC, danieledamiani requested changes
a comment

2022-01-11 18:32 UTC, lazarmitic commented on packages/tempus-client_v2/src/components/profitLoss/profitLossChart/ProfitLossChart.tsx
> +    if (!lastChartEntry) {
Yeah, but TypeScript does not get that, return type on pop is <ChartDataPoint | undefined>. So I have to check, otherwise TypeScript complains.

2022-01-12 08:26 UTC, danieledamiani approved these changes

2022-01-12 08:47 UTC, merged