unit test for src/services/VaultService.ts
tempus-finance/tempus-app pull request #674
Opened 2022-01-07 09:25 UTC by ShawTim

2022-01-07 10:11 UTC, danieledamiani commented on packages/tempus-client_v2/src/services/VaultService.test.ts
> +    address: "0x0000000000000000000000000000000000000000",
this value is the same as `DUMMY_ADDR` so this can be `address: DUMMY_ADDR`

2022-01-07 10:13 UTC, danieledamiani commented on packages/tempus-client_v2/src/services/VaultService.test.ts
> +jest.mock("@ethersproject/providers", () => ({
our code style uses single quotes, can you check you have the Prettier extension installed in VSC?

2022-01-07 10:14 UTC, danieledamiani commented on packages/tempus-client_v2/src/services/VaultService.test.ts
> +      Contract: Contract,
use Javascript shortcut:
```
vaultService.init({
      Contract,
...
```

2022-01-07 10:16 UTC, danieledamiani commented on packages/tempus-client_v2/src/services/VaultService.test.ts
> +    test("test with no init() invoked", async () => {
the test description should describe what the test result is. In this case something like "returns an error if method called before init()"

2022-01-07 10:16 UTC, danieledamiani commented on packages/tempus-client_v2/src/services/VaultService.test.ts
> +    test("test with no tempusAMMService provided", async () => {
same as above

2022-01-07 10:41 UTC, ShawTim commented on packages/tempus-client_v2/src/services/VaultService.test.ts
> +    address: "0x0000000000000000000000000000000000000000",
done

2022-01-07 10:42 UTC, ShawTim commented on packages/tempus-client_v2/src/services/VaultService.test.ts
> +jest.mock("@ethersproject/providers", () => ({
done

2022-01-07 10:43 UTC, ShawTim commented on packages/tempus-client_v2/src/services/VaultService.test.ts
> +    test("test with no init() invoked", async () => {
update all test describe with "xxxx should reject with error" / "xxxx should return with xxxx" pattern

2022-01-07 10:43 UTC, ShawTim commented on packages/tempus-client_v2/src/services/VaultService.test.ts
> +    test("test with no tempusAMMService provided", async () => {
update all test describe with "xxxx should reject with error" / "xxxx should return with xxxx" pattern

2022-01-07 10:47 UTC, ShawTim commented on packages/tempus-client_v2/src/services/VaultService.test.ts
> +      Contract: Contract,
done

2022-01-10 11:48 UTC, danieledamiani commented on packages/tempus-client_v2/src/services/VaultService.test.ts
> +      const fromAddress = '0x0000000000000000000000000000000000000000';
it's `DUMMY_ADDR`

2022-01-10 11:51 UTC, danieledamiani commented on packages/tempus-client_v2/src/services/VaultService.test.ts
> +        .mockReturnValue({ getBlock: mockGetBlock } as unknown as JsonRpcProvider);
twice `as` ?

2022-01-10 11:52 UTC, danieledamiani commented on packages/tempus-client_v2/src/services/VaultService.test.ts
> +      const userWalletAddress = '0x0000000000000000000000000000000000000000';
it's `DUMMY_ADDR`, please change whenever the same value occours again

2022-01-10 11:53 UTC, danieledamiani requested changes
a few comments, looks good to me

2022-01-10 15:08 UTC, ShawTim commented on packages/tempus-client_v2/src/services/VaultService.test.ts
> +        .mockReturnValue({ getBlock: mockGetBlock } as unknown as JsonRpcProvider);
these double assertion fixes are suggested by VS code
https://basarat.gitbook.io/typescript/type-system/type-assertion#double-assertion

we can set it as `any` type to make it works:
- for `any`, no double assertion, it works. but we may not know what type it is
- for double assertion, but we know what type it is during development time

which one do we prefer?

2022-01-10 15:17 UTC, ShawTim commented on packages/tempus-client_v2/src/services/VaultService.test.ts
> +      const fromAddress = '0x0000000000000000000000000000000000000000';
done, use `DUMMY_ADDR` instead

2022-01-10 15:17 UTC, ShawTim commented on packages/tempus-client_v2/src/services/VaultService.test.ts
> +      const userWalletAddress = '0x0000000000000000000000000000000000000000';
done, use `DUMMY_ADDR` instead

2022-01-10 15:17 UTC, ShawTim commented on packages/tempus-client_v2/src/services/VaultService.test.ts
> +      const fromAddress = '0x0000000000000000000000000000000000000000';
done, use `DUMMY_ADDR` instead

2022-01-10 15:50 UTC, danieledamiani commented on packages/tempus-client_v2/src/services/VaultService.test.ts
> +        .mockReturnValue({ getBlock: mockGetBlock } as unknown as JsonRpcProvider);
ok let's keep the double assertion

2022-01-10 17:00 UTC, merged